version: "3.7"
services:
  app:
    build:
      args:
        user: web
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: dbuser
      DB_PASSWORD: password
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_PASSWORD: password
      MYSQL_USER: dbuser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel


  webserver:
    build:
      args:
        user: web
        uid: 1000
      context: ./
      dockerfile: Dockerfile.nginx
    image: nginx
    container_name: laravel-web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
