version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - "db"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: rootpw

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_PASSWORD: password
      MYSQL_USER: dbuser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql


  webserver:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: nginx
    container_name: laravel-web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"

