name: Laravel

on:
  push:
    branches: [ master,staging,develop ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
  deploy-images:

    runs-on: ubuntu-latest
    needs: laravel-tests
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Extract tag name
      shell: bash
      run: |
        BRANCH=echo ${GITHUB_REF#refs/heads/}
        if [ "$BRANCH" = "master" ]; then
          echo "##[set-output name=tag;]$(echo "lastest")"
        else
          echo "##[set-output name=tag;]$(echo ${BRANCH})"
        fi        
      id: set_tag
    - name: Set outputs
      id: sha_short
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs tag
      run: echo ${{ steps.set_tag.outputs.tag }}
    - name: Check outputs sha
      run: echo ${{ steps.sha_short.outputs.sha_short }}
    - name: AWS ECR App
      uses: kciter/aws-ecr-action@v2
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: cdk_laravel/laravel
        region: ${{ secrets.AWS_REGION }}
        tags: ${{ steps.set_tag.outputs.tag }},${{ steps.sha_short.outputs.sha_short }}
        create_repo: true
        dockerfile: Dockerfile
        
    - name: AWS ECR Nginx
      uses: kciter/aws-ecr-action@v2
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: cdk_laravel/nginx
        region: ${{ secrets.AWS_REGION }}
        tags: ${{ steps.set_tag.outputs.tag }},${{ steps.sha_short.outputs.sha_short }}
        create_repo: true
        dockerfile: Dockerfile.nginx
